// Code generated by go-swagger; DO NOT EDIT.

// Package restapi http-go-server
//
//  HTTP server in Go with Swagger endpoints definition
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
