// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGopherNameHandlerFunc turns a function with the right signature into a get gopher name handler
type GetGopherNameHandlerFunc func(GetGopherNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGopherNameHandlerFunc) Handle(params GetGopherNameParams) middleware.Responder {
	return fn(params)
}

// GetGopherNameHandler interface for that can handle valid get gopher name params
type GetGopherNameHandler interface {
	Handle(GetGopherNameParams) middleware.Responder
}

// NewGetGopherName creates a new http.Handler for the get gopher name operation
func NewGetGopherName(ctx *middleware.Context, handler GetGopherNameHandler) *GetGopherName {
	return &GetGopherName{Context: ctx, Handler: handler}
}

/*
	GetGopherName swagger:route GET /gopher/{name} getGopherName

Return the Gopher Image.
*/
type GetGopherName struct {
	Context *middleware.Context
	Handler GetGopherNameHandler
}

func (o *GetGopherName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGopherNameParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
